# Generated by Django 5.1.7 on 2025-03-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='logo',
            new_name='marca',
        ),
    ]
