# Generated by Django 5.1.7 on 2025-03-26 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_logo_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Talla de producto',
                'verbose_name_plural': 'Tallas de productos',
                'unique_together': {('producto', 'talla')},
            },
        ),
    ]
