# Generated by Django 5.1.7 on 2025-03-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_tallaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/imagenes/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['orden'],
            },
        ),
    ]
