# Generated by Django 5.1.7 on 2025-03-28 12:02

from django.db import migrations

def ensure_one_principal_image(apps, schema_editor):
    """
    Asegurar que cada producto tenga exactamente una imagen principal.
    Si no tiene ninguna, se marca la primera como principal.
    Si tiene múltiples, se mantiene solo la primera como principal.
    """
    Producto = apps.get_model('catalogo', 'Producto')
    ImagenProducto = apps.get_model('catalogo', 'ImagenProducto')
    
    # Para cada producto
    for producto in Producto.objects.all():
        imagenes = ImagenProducto.objects.filter(producto=producto).order_by('orden')
        
        # Si hay imágenes pero ninguna principal
        if imagenes.exists() and not imagenes.filter(es_principal=True).exists():
            primera_imagen = imagenes.first()
            primera_imagen.es_principal = True
            primera_imagen.save()
        
        # Si hay múltiples imágenes principales
        principales = list(imagenes.filter(es_principal=True))
        if len(principales) > 1:
            # Mantener solo la primera como principal
            for img in principales[1:]:
                img.es_principal = False
                img.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_imagenproducto'),
    ]

    operations = [
    ]
