# Generated by Django 5.1.7 on 2025-03-28 16:20

import catalogo.models
from django.db import migrations, models


def check_existing_images(apps, schema_editor):
    """
    Verifica las imágenes existentes y muestra un warning para las muy grandes
    """
    ImagenProducto = apps.get_model('catalogo', 'ImagenProducto')
    max_size = 5 * 1024 * 1024  # 5MB
    
    large_images = []
    for img in ImagenProducto.objects.all():
        if img.imagen and hasattr(img.imagen, 'size') and img.imagen.size > max_size:
            large_images.append((img.id, img.imagen.name, img.imagen.size))
    
    if large_images:
        print("\n¡ADVERTENCIA! Las siguientes imágenes exceden el límite de 5MB:")
        for img_id, name, size in large_images:
            print(f"  - ID: {img_id}, Nombre: {name}, Tamaño: {size/1024/1024:.2f}MB")
        print("Estas imágenes podrían causar problemas cuando se aplique el validador.\n")

class Migration(migrations.Migration):
    dependencies = [
        ('catalogo', '0004_imagenproducto'),  # Ajusta según tu última migración
    ]

    operations = [
        migrations.RunPython(check_existing_images, migrations.RunPython.noop),
    ]
