# Generated by Django 5.1.7 on 2025-03-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_ensure_one_principal_image'),
        ('catalogo', '0006_alter_imagenproducto_imagen_and_more'),
    ]

    operations = [
    ]
