# Generated by Django 5.1.7 on 2025-03-29 00:19

import catalogo.models
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_merge_20250328_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['orden', '-es_principal'], 'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de productos'},
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='fecha_creacion',
            field=models.DateTimeField(default=catalogo.models.get_default_date, help_text='Fecha de creación de la imagen'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Marcar como imagen principal del producto'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=imagekit.models.fields.ProcessedImageField(help_text='Tamaño máximo: 5MB. Se redimensionará automáticamente.', upload_to='productos/imagenes/', validators=[catalogo.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la galería (menor número = aparece primero)'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título descriptivo para SEO y accesibilidad', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='imagenproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'orden'), name='unique_product_image_order'),
        ),
    ]
