# Generated by Django 5.1.7 on 2025-03-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_imagenproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la imagen'),
        ),
    ]
