# Generated by Django 5.1.7 on 2025-03-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_imagenproducto_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagenproducto',
            name='unique_product_image_order',
        ),
    ]
